name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20  # Adjust this to your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Vue.js project
        run: npm run build  # Modify this if your project uses a different build command

      - name: Build Docker image
        run: docker build -t meetlocal-frontend:latest .
        
      - name: Push Docker image to Docker Hub
        uses: docker/login-action@v1
        with:
          username: yourdockerusername
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Tag and push Docker image
        run: |
          docker tag meetlocal-frontend:latest yourdockerusername/meetlocal-frontend:latest
          docker push yourdockerusername/meetlocal-frontend:latest



      - name: Deploy Docker container
        run: |
          docker pull caettus/meetlocal-frontend:latest
          docker stop meetlocal-frontend || true
          docker rm meetlocal-frontend || true
          docker run -d --name meetlocal-frontend -p 80:80 caettus/meetlocal-frontend:latest
